# Inserts a blank line between shell prompts
add_newline = true

command_timeout = 2000

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
error_symbol = '[✗](bold red)'

[cmd_duration]
disabled = true
style = 'dimmed gray'

[directory]
style = 'bold blue'
# truncation_length = 3
# truncate_to_repo = false
truncation_symbol = ' '

[git_metrics]
disabled = false

[hostname]
ssh_only = true
# aliases = { "lm21" = "🐧" }

# [line_break]
# disabled = true

[golang]
symbol = " "

[python]
symbol = " "

[nodejs]
symbol = " "

[dart]
symbol = " "

[lua]
symbol = " "

[rust]
symbol = " "

[c]
symbol = " "

[docker_context]
symbol = " "

[zig]
symbol = "  "
detect_files = ["build.zig", "build.zig.zon"]
